services:

    pgdb:
      image: postgres
      container_name: postgres
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: 1234
      volumes:
        - ./docker-volumes/pgdb:/var/lib/postgresql/data
      networks:
        - dotnet

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4
      ports:
        - "8888:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@gmail.com
        PGADMIN_DEFAULT_PASSWORD: 1234
      volumes:
        - ./docker-volumes/pgadmin:/var/lib/pgadmin
      networks:
        - dotnet
  
    app:
      image: dotnet-app
      container_name: dotnet-app
      build: .
      restart: always
      ports:
        - "8080:8080"
      depends_on:
        - pgdb
      environment:
        - DB_HOST=pgdb
        - DB_PORT=5432
        - DB_NAME=postgres
        - DB_USER=admin
        - DB_PASS=1234
        - ASPNETCORE_ENVIRONMENT=Development
      networks:
      - dotnet


networks:
  dotnet:
    driver: bridge
